//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pea.Meter.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pea.Meter.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#10;• Flat rate total cost: .
        /// </summary>
        public static string _10FlatRateTotalCost {
            get {
                return ResourceManager.GetString("_10FlatRateTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days Summary.
        /// </summary>
        public static string _30DaysSummary {
            get {
                return ResourceManager.GetString("_30DaysSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comparison between the Time-of-Use (TOU) tariff and the Flat Rate tariff shows the financial impact under the current consumption pattern..
        /// </summary>
        public static string AComparisonBetweenTheTimeOfUseTOUTariffAndTheFlatRateTariffShowsTheFinancialImpactUnderTheCurrentConsumptionPattern {
            get {
                return ResourceManager.GetString("AComparisonBetweenTheTimeOfUseTOUTariffAndTheFlatRateTariffShowsTheFinancialImpac" +
                        "tUnderTheCurrentConsumptionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Historic Readings.
        /// </summary>
        public static string AllHistoricReadings {
            get {
                return ResourceManager.GetString("AllHistoricReadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Meter Readings.
        /// </summary>
        public static string AllMeterReadings {
            get {
                return ResourceManager.GetString("AllMeterReadings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average usage (30 days).
        /// </summary>
        public static string AverageUsage30Days {
            get {
                return ResourceManager.GetString("AverageUsage30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average usage (7 days).
        /// </summary>
        public static string AverageUsage7Days {
            get {
                return ResourceManager.GetString("AverageUsage7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average usage (Yesterday).
        /// </summary>
        public static string AverageUsageYesterday {
            get {
                return ResourceManager.GetString("AverageUsageYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath Per Month.
        /// </summary>
        public static string BathPerMonth {
            get {
                return ResourceManager.GetString("BathPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Binding Item.OffPeekFormatted, StringFormat=&apos;Off-peak: {0}&apos;}.
        /// </summary>
        public static string BindingItemOffPeekFormattedStringFormatOffPeak0 {
            get {
                return ResourceManager.GetString("BindingItemOffPeekFormattedStringFormatOffPeak0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Binding Item.PeekFormatted, StringFormat=&apos;Peak: {0}&apos;}.
        /// </summary>
        public static string BindingItemPeekFormattedStringFormatPeak0 {
            get {
                return ResourceManager.GetString("BindingItemPeekFormattedStringFormatPeak0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Binding Item.TotalFormatted, StringFormat=&apos;Total: {0}&apos;}.
        /// </summary>
        public static string BindingItemTotalFormattedStringFormatTotal0 {
            get {
                return ResourceManager.GetString("BindingItemTotalFormattedStringFormatTotal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive diagnostic testing, oil analysis, and preventative repairs to ensure grid stability and peak electrical efficiency.
        /// </summary>
        public static string ComprehensiveDiagnosticTestingOil {
            get {
                return ResourceManager.GetString("ComprehensiveDiagnosticTestingOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Calculation.
        /// </summary>
        public static string CostCalculation {
            get {
                return ResourceManager.GetString("CostCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profile.
        /// </summary>
        public static string CustomerProfile {
            get {
                return ResourceManager.GetString("CustomerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo account.
        /// </summary>
        public static string DemoAccount {
            get {
                return ResourceManager.GetString("DemoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Tariff Comparison Summary.
        /// </summary>
        public static string ElectricityTariffComparisonSummary {
            get {
                return ResourceManager.GetString("ElectricityTariffComparisonSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Billing.
        /// </summary>
        public static string ElectronicBilling {
            get {
                return ResourceManager.GetString("ElectronicBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date - .
        /// </summary>
        public static string EndDate_dash {
            get {
                return ResourceManager.GetString("EndDate_dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption in KW per Day.
        /// </summary>
        public static string EnergyConsumptionInKWPerDay {
            get {
                return ResourceManager.GetString("EnergyConsumptionInKWPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy consumption in KW per Hour.
        /// </summary>
        public static string EnergyConsumptionInKWPerHour {
            get {
                return ResourceManager.GetString("EnergyConsumptionInKWPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation Of Solar Array Size.
        /// </summary>
        public static string EstimationOfSolarArraySize {
            get {
                return ResourceManager.GetString("EstimationOfSolarArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatRate.
        /// </summary>
        public static string FlatRate {
            get {
                return ResourceManager.GetString("FlatRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result indicates significant electricity usage during peak-rate hours, where TOU pricing is higher. Unless consumption shifts to off-peak periods, the Flat Rate tariff remains the more cost-efficient choice..
        /// </summary>
        public static string FlatRateInConclusionBased {
            get {
                return ResourceManager.GetString("FlatRateInConclusionBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatRate Price.
        /// </summary>
        public static string FlatRatePrice {
            get {
                return ResourceManager.GetString("FlatRatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatRate Solar.
        /// </summary>
        public static string FlatRateSolar {
            get {
                return ResourceManager.GetString("FlatRateSolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go paperless in Thailand! Save time and trees by getting secure monthly invoices sent to your inbox..
        /// </summary>
        public static string GoPaperlessInThailand {
            get {
                return ResourceManager.GetString("GoPaperlessInThailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % higher cost compared to the Flat Rate option..
        /// </summary>
        public static string HigherCostComparedToTheFlatRateOption {
            get {
                return ResourceManager.GetString("HigherCostComparedToTheFlatRateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Note: .
        /// </summary>
        public static string ImportantNote {
            get {
                return ResourceManager.GetString("ImportantNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Day (Day in month).
        /// </summary>
        public static string InvoiceDayDayInMonth {
            get {
                return ResourceManager.GetString("InvoiceDayDayInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWh per 15 minute.
        /// </summary>
        public static string KWhPer15Minute {
            get {
                return ResourceManager.GetString("KWhPer15Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWh Per Month.
        /// </summary>
        public static string KWhPerMonth {
            get {
                return ResourceManager.GetString("KWhPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % lower cost compared to the flat rate option..
        /// </summary>
        public static string LowerCostComparedToTheFlatRateOption {
            get {
                return ResourceManager.GetString("LowerCostComparedToTheFlatRateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEA Smart Meter.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string MeterNumber {
            get {
                return ResourceManager.GetString("MeterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 6 characters.
        /// </summary>
        public static string Minimum6Characters {
            get {
                return ResourceManager.GetString("Minimum6Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, a demo account will be enough.
        /// </summary>
        public static string NoADemoAccountWillBeEnough {
            get {
                return ResourceManager.GetString("NoADemoAccountWillBeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffPeak Price.
        /// </summary>
        public static string OffPeakPrice {
            get {
                return ResourceManager.GetString("OffPeakPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffPeek.
        /// </summary>
        public static string OffPeek {
            get {
                return ResourceManager.GetString("OffPeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffPeek Solar.
        /// </summary>
        public static string OffPeekSolar {
            get {
                return ResourceManager.GetString("OffPeekSolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {OnIdiom Desktop=&apos;Transformer Lifecycle Management&apos;, Default=&apos;Transformer Management&apos;}.
        /// </summary>
        public static string OnIdiomDesktopTransformerLifecycleManagementDefaultTransformerManagement {
            get {
                return ResourceManager.GetString("OnIdiomDesktopTransformerLifecycleManagementDefaultTransformerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview Per Day.
        /// </summary>
        public static string OverviewPerDay {
            get {
                return ResourceManager.GetString("OverviewPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEA.
        /// </summary>
        public static string PEA {
            get {
                return ResourceManager.GetString("PEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Price.
        /// </summary>
        public static string PeakPrice {
            get {
                return ResourceManager.GetString("PeakPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEA SOLAR.
        /// </summary>
        public static string PEASOLAR {
            get {
                return ResourceManager.GetString("PEASOLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek.
        /// </summary>
        public static string Peek {
            get {
                return ResourceManager.GetString("Peek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek Solar.
        /// </summary>
        public static string PeekSolar {
            get {
                return ResourceManager.GetString("PeekSolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Start.
        /// </summary>
        public static string PeriodStart {
            get {
                return ResourceManager.GetString("PeriodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware .
        /// </summary>
        public static string PleaseBeAware {
            get {
                return ResourceManager.GetString("PleaseBeAware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to bring in your history?.
        /// </summary>
        public static string ReadyToBringInYourHistory {
            get {
                return ResourceManager.GetString("ReadyToBringInYourHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Obtain credential.
        /// </summary>
        public static string Register_1ObtainCredentialX0a {
            get {
                return ResourceManager.GetString("Register_1ObtainCredentialX0a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Credential sent from PEA.
        /// </summary>
        public static string Register_2CredentialSentFromPEA {
            get {
                return ResourceManager.GetString("Register_2CredentialSentFromPEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Start registration.
        /// </summary>
        public static string Register_3StartRegistration {
            get {
                return ResourceManager.GetString("Register_3StartRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Register Your Electric Meter.
        /// </summary>
        public static string Register_HowToRegisterYourElectricMeter {
            get {
                return ResourceManager.GetString("Register_HowToRegisterYourElectricMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look in your inbox for a mail from .
        /// </summary>
        public static string Register_LookInYourInboxForAMailFrom {
            get {
                return ResourceManager.GetString("Register_LookInYourInboxForAMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read instruction in the .
        /// </summary>
        public static string Register_ReadInstructionInThe {
            get {
                return ResourceManager.GetString("Register_ReadInstructionInThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Meter Account.
        /// </summary>
        public static string Register_RegisterMeterAccount {
            get {
                return ResourceManager.GetString("Register_RegisterMeterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.amr..
        /// </summary>
        public static string Register_SupportAmr {
            get {
                return ResourceManager.GetString("Register_SupportAmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the green button below to get started..
        /// </summary>
        public static string Register_TapTheGreenButtonBelowToGetStarted {
            get {
                return ResourceManager.GetString("Register_TapTheGreenButtonBelowToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want to register a Meter.
        /// </summary>
        public static string Register_YesIWantToRegisterAMeter {
            get {
                return ResourceManager.GetString("Register_YesIWantToRegisterAMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a date will immediately start the process of bringing in your information. .
        /// </summary>
        public static string SelectingADateWillImmediatelyStartTheProcessOfBringingInYourInformation {
            get {
                return ResourceManager.GetString("SelectingADateWillImmediatelyStartTheProcessOfBringingInYourInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Services.
        /// </summary>
        public static string SmartServices {
            get {
                return ResourceManager.GetString("SmartServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar.
        /// </summary>
        public static string Solar {
            get {
                return ResourceManager.GetString("Solar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar System Calculation (Experimental).
        /// </summary>
        public static string SolarSystemCalculationExperimental {
            get {
                return ResourceManager.GetString("SolarSystemCalculationExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date - .
        /// </summary>
        public static string StartDate_dash {
            get {
                return ResourceManager.GetString("StartDate_dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Importing Historical Data....
        /// </summary>
        public static string StartImportingHistoricalData {
            get {
                return ResourceManager.GetString("StartImportingHistoricalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainable solar for farms and homes. Powering irrigation and off-grid life 24/7 with zero emissions.
        /// </summary>
        public static string SustainableSolarForFarmsAndHomes {
            get {
                return ResourceManager.GetString("SustainableSolarForFarmsAndHomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift, paperless, and global. Securely access all our services from any device, anywhere on Earth.
        /// </summary>
        public static string SwiftPaperlessAndGlobalSecurelyAccess {
            get {
                return ResourceManager.GetString("SwiftPaperlessAndGlobalSecurelyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff.
        /// </summary>
        public static string Tariff {
            get {
                return ResourceManager.GetString("Tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Calculation.
        /// </summary>
        public static string TariffCalculation {
            get {
                return ResourceManager.GetString("TariffCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Flat rate total cost:.
        /// </summary>
        public static string TariffCalculation_FlatRateTotalCost {
            get {
                return ResourceManager.GetString("TariffCalculation_FlatRateTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • TOU total cost:.
        /// </summary>
        public static string TariffCalculation_TOUTotalCost {
            get {
                return ResourceManager.GetString("TariffCalculation_TOUTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that any data you have already added will be permanently removed to make room for the new history. .
        /// </summary>
        public static string ThatAnyDataYouHaveAlreadyAddedWillBePermanentlyRemovedToMakeRoomForTheNewHistory {
            get {
                return ResourceManager.GetString("ThatAnyDataYouHaveAlreadyAddedWillBePermanentlyRemovedToMakeRoomForTheNewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  THB, equivalent to approximately .
        /// </summary>
        public static string THBEquivalentToApproximately {
            get {
                return ResourceManager.GetString("THBEquivalentToApproximately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  THB, more expensive, representing a .
        /// </summary>
        public static string THBMoreExpensiveRepresentingA {
            get {
                return ResourceManager.GetString("THBMoreExpensiveRepresentingA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ensures your records stay organized and up to date..
        /// </summary>
        public static string ThisEnsuresYourRecordsStayOrganizedAndUpToDate {
            get {
                return ResourceManager.GetString("ThisEnsuresYourRecordsStayOrganizedAndUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means the TOU tariff is .
        /// </summary>
        public static string ThisMeansTheTOUTariffIs {
            get {
                return ResourceManager.GetString("ThisMeansTheTOUTariffIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means the TOU tariff results in a savings of .
        /// </summary>
        public static string ThisMeansTheTOUTariffResultsInASavingsOf {
            get {
                return ResourceManager.GetString("ThisMeansTheTOUTariffResultsInASavingsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Of Use.
        /// </summary>
        public static string TimeOfUse {
            get {
                return ResourceManager.GetString("TimeOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comparison between the Time-of-Use (TOU) tariff and the Flat Rate tariff shows a clear financial advantage for TOU under the current consumption pattern..
        /// </summary>
        public static string ToUComparisonBetweenTheTimeOfUseTOUTariff {
            get {
                return ResourceManager.GetString("ToUComparisonBetweenTheTimeOfUseTOUTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In conclusion, based on current data, the TOU tariff is the more economical choice, delivering meaningful cost savings without requiring changes in overall consumption..
        /// </summary>
        public static string ToUInConclusionBased {
            get {
                return ResourceManager.GetString("ToUInConclusionBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU total cost: .
        /// </summary>
        public static string TOUTotalCost_ {
            get {
                return ResourceManager.GetString("TOUTotalCost_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer Lifecycle Management.
        /// </summary>
        public static string TransformerLifecycleManagement {
            get {
                return ResourceManager.GetString("TransformerLifecycleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer Management.
        /// </summary>
        public static string TransformerManagement {
            get {
                return ResourceManager.GetString("TransformerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Tariff.
        /// </summary>
        public static string TypeOfTariff {
            get {
                return ResourceManager.GetString("TypeOfTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the calendar below to pick the day you want your records to start..
        /// </summary>
        public static string UseTheCalendarBelowToPickTheDayYouWantYourRecordsToStart {
            get {
                return ResourceManager.GetString("UseTheCalendarBelowToPickTheDayYouWantYourRecordsToStart", resourceCulture);
            }
        }
    }
}
