// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pea.Data;

#nullable disable

namespace Pea.Data.Migrations
{
    [DbContext(typeof(PeaDbContext))]
    partial class PeaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Pea.Data.Entities.MeterReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RateB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RateC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PeriodStart")
                        .IsUnique();

                    b.ToTable("MeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
