name: PEA Smart Meter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: windows-latest
    steps:
      - name: Check dotnet on first run
        run: dotnet --version
      - uses: actions/checkout@v3
        
      - name: Setup Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" > pea.smart.meter.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch pea.smart.meter.keystore.asc > .\Pea.Meter\pea.smart.meter.keystore
          
      - name: Validate Keystore File
        run: |
          if (Test-Path ".\Pea.Meter\pea.smart.meter.keystore") {
            Write-Host "Keystore file exists"
          } else {
            Write-Error "Keystore file not found"
            exit 1
          }
      
      - name: Print current directory
        run: pwd
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Print directory
        run: pwd
            
      - name: Build
        run: dotnet publish Pea.Meter/Pea.Meter.csproj -verbosity:detailed -f net10.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=pea.smart.meter.keystore -p:AndroidSigningKeyAlias=ghactionkey -p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}"
      - name: List build output
        run: ls -R ./**/*-Signed.aab
      - uses: r0adkll/upload-google-play@v1.1.3
        name: Upload Android Artifact to Play Console
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
          packageName: com.ivdata.pea.smart.meter
          releaseFiles: Pea.Meter/bin/Release/net10.0-android/publish/com.ivdata.pea.smart.meter-Signed.aab
          track: internal
